In [1]:
import tensorflow as tf
import numpy as np
import re
import os
from sklearn.metrics import classification_report

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
with open('entities-bm.txt','r') as fopen:
    texts= list(filter(None, fopen.read().split('\n')))
len(texts)

12194

In [3]:
train_texts = texts
# dataset is too small
test_texts = texts

In [4]:
word2idx = {'PAD': 0,'NUM':1,'UNK':2}
tag2idx = {'PAD': 0}
char2idx = {'PAD': 0}
word_idx = 3
tag_idx = 1
char_idx = 1

In [5]:
def process_word(word, lower=True):
    if lower:
        word = word.lower()
    else:
        if word.isupper():
            word = word.title()
    word = re.sub('[^A-Za-z0-9\- ]+', '', word)
    if word.isdigit():
        word = 'NUM'
    return word

def read_file(f):
    global word_idx, tag_idx, char_idx
    words, tags, X, Y = [], [], [], []
    for line in f:
        line = line.strip()
        if (len(line) == 0 or line.startswith("-DOCSTART-")):
            continue
        else:
            ls = line.split(' ')
            if len(ls) > 1:
                word, tag = ls[0],ls[-1]
            else:
                word = ls[0]
                tag = 'O'
            for c in word:
                if c not in char2idx:
                    char2idx[c] = char_idx
                    char_idx += 1
            word = process_word(word)
            if len(word) < 1:
                continue
            words += [word]
            tags += [tag]
            if word not in word2idx:
                word2idx[word] = word_idx
                word_idx += 1
            X.append(word2idx[word])
            if tag not in tag2idx:
                tag2idx[tag] = tag_idx
                tag_idx += 1
            Y.append(tag2idx[tag])
                        
    return words, tags, X, Y

In [6]:
train_words, train_tags, train_X, train_Y = read_file(train_texts)
test_words, test_tags, test_X, test_Y = read_file(test_texts)

In [7]:
idx2tag={idx: tag for tag, idx in tag2idx.items()}
idx2word={idx: tag for tag, idx in word2idx.items()}
batch_size = 16
dim_word = 128
dim_char = 32
dropout = 0.8
learning_rate = 1e-2
hidden_size_char = 64
hidden_size_word = 128
num_layers = 2
seq_len = 20
display_step = 200
epoch = 20

In [8]:
class Model:
    def __init__(self, dim_word, dim_char, dropout, learning_rate,
                 hidden_size_char, hidden_size_word, num_layers):
        
        def cells(size, reuse=False):
            return tf.nn.rnn_cell.LSTMCell(size,initializer=tf.orthogonal_initializer(),reuse=reuse)
        
        def clip_grads(loss):
            variables = tf.trainable_variables()
            grads = tf.gradients(loss, variables)
            clipped_grads, _ = tf.clip_by_global_norm(grads, 5.0)
            return zip(clipped_grads, variables)
        
        self.word_ids = tf.placeholder(tf.int32, shape=[None, None])
        self.sequence_lengths = tf.placeholder(tf.int32, shape=[None])
        self.char_ids = tf.placeholder(tf.int32, shape=[None, None, None])
        self.word_lengths = tf.placeholder(tf.int32, shape=[None, None])
        self.labels = tf.placeholder(tf.int32, shape=[None, None])
        
        self.word_embeddings = tf.Variable(tf.truncated_normal([len(word2idx), dim_word],
                                                      stddev=1.0 / np.sqrt(dim_word)))
        self.char_embeddings = tf.Variable(tf.truncated_normal([len(char2idx), dim_char],
                                                      stddev=1.0 / np.sqrt(dim_char)))
        word_embedded = tf.nn.embedding_lookup(self.word_embeddings, self.word_ids)
        char_embedded = tf.nn.embedding_lookup(self.char_embeddings, self.char_ids)
        s = tf.shape(char_embedded)
        char_embedded = tf.reshape(char_embedded, shape=[s[0]*s[1], s[-2], dim_char])
        word_lengths = tf.reshape(self.word_lengths, shape=[s[0]*s[1]])
        for n in range(num_layers):
            (out_fw, out_bw), (state_fw, state_bw) = tf.nn.bidirectional_dynamic_rnn(
                cell_fw = cells(hidden_size_char),
                cell_bw = cells(hidden_size_char),
                inputs = char_embedded,
                dtype = tf.float32,
                sequence_length=word_lengths,
                scope = 'bidirectional_rnn_char_%d'%(n))
            char_embedded = tf.concat((out_fw, out_bw), 2)
        output = tf.reshape(char_embedded[:,-1], shape=[s[0], s[1], 2*hidden_size_char])
        word_embedded = tf.concat([word_embedded, output], axis=-1)
        word_embedded = tf.nn.dropout(word_embedded, dropout)
        
        for n in range(num_layers):
            (out_fw, out_bw), (state_fw, state_bw) = tf.nn.bidirectional_dynamic_rnn(
                cell_fw = cells(hidden_size_word),
                cell_bw = cells(hidden_size_word),
                inputs = word_embedded,
                sequence_length=self.sequence_lengths, 
                dtype=tf.float32,
                scope = 'bidirectional_rnn_word_%d'%(n))
            word_embedded = tf.concat((out_fw, out_bw), 2)
        word_embedded = tf.nn.dropout(word_embedded, dropout)
        
        W = tf.get_variable('w',shape=(2*hidden_size_word, len(idx2tag)),
                            initializer=tf.orthogonal_initializer())
        b = tf.get_variable('b',shape=(len(idx2tag)),initializer=tf.zeros_initializer())
        
        nsteps = tf.shape(word_embedded)[1]
        output = tf.reshape(word_embedded, [-1, 2*hidden_size_word])
        pred = tf.matmul(output, W) + b
        self.logits = tf.reshape(pred, [-1, nsteps, len(idx2tag)])
        
        log_likelihood, trans_params = tf.contrib.crf.crf_log_likelihood(
        self.logits, self.labels, tf.count_nonzero(self.word_ids, 1))
        
        self.cost = tf.reduce_mean(-log_likelihood)
        self.global_step = tf.Variable(0, trainable=False)
        
        self.crf_decode = tf.contrib.crf.crf_decode(self.logits, 
                                                    trans_params, 
                                                    tf.count_nonzero(self.word_ids, 1))[0]
        
        self.optimizer = tf.train.AdamOptimizer(learning_rate).apply_gradients(clip_grads(self.cost), 
                                                                                    global_step=self.global_step)

In [9]:
tf.reset_default_graph()
sess = tf.InteractiveSession()
model = Model(dim_word,dim_char,dropout,learning_rate,hidden_size_char,hidden_size_word,num_layers)
sess.run(tf.global_variables_initializer())

/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


In [10]:
def iter_seq(x):
    return np.array([x[i: i+seq_len] for i in range(0, len(x)-seq_len, 1)])

def to_train_seq(*args):
    return [iter_seq(x) for x in args]

def generate_char_seq(batch):
    x = [[len(idx2word[i]) for i in k] for k in batch]
    maxlen = max([j for i in x for j in i])
    temp = np.zeros((batch.shape[0],batch.shape[1],maxlen),dtype=np.int32)
    for i in range(batch.shape[0]):
        for k in range(batch.shape[1]):
            for no, c in enumerate(idx2word[batch[i,k]]):
                temp[i,k,no] = char2idx[c]
    return temp, np.array(x,dtype=np.int32)

In [11]:
train_X_seq, train_Y_seq = to_train_seq(train_X, train_Y)
test_X_seq, test_Y_seq = to_train_seq(test_X, test_Y)

In [12]:
np.unique(train_Y_seq.ravel(),return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([  8063, 185166,  23771,   2600,   6080,   2120,   2120,  10280,
          1280,   1860,     20]))

In [13]:
np.unique(test_Y_seq.ravel(),return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([  8063, 185166,  23771,   2600,   6080,   2120,   2120,  10280,
          1280,   1860,     20]))

In [14]:
idx2tag

{0: 'PAD',
 1: 'LOC',
 2: 'O',
 3: 'PRN',
 4: 'ORG',
 5: 'TIME',
 6: 'ART',
 7: 'EVENT',
 8: 'NORP',
 9: 'FAC',
 10: 'LAW',
 11: 'DOC'}

In [15]:
for i in range(epoch):
    total_cost = 0
    for k in range(0,(train_X_seq.shape[0] // batch_size)*batch_size,batch_size):
        batch_x = train_X_seq[k:k+batch_size]
        batch_y = train_Y_seq[k:k+batch_size]
        batch_length = [seq_len] * batch_size
        batch_x_char, batch_x_char_length = generate_char_seq(batch_x)
        step, loss, _ = sess.run([model.global_step, model.cost, model.optimizer],
                                 feed_dict={model.word_ids:batch_x,
                                           model.sequence_lengths:batch_length,
                                           model.char_ids:batch_x_char,
                                           model.word_lengths:batch_x_char_length,
                                           model.labels:batch_y})
        if step % display_step == 0 or step == 1:
            print('epoch %d, step %d, loss %f'%(i+1,step,loss))
        total_cost += loss
    total_cost /= (train_X_seq.shape[0] // batch_size)
    print('epoch %d, avg loss %f'%(i+1,total_cost))

epoch 1, step 1, loss 55.154758
epoch 1, step 200, loss 2.997496
epoch 1, step 400, loss 2.384757
epoch 1, step 600, loss 10.292503
epoch 1, avg loss 11.713000
epoch 2, step 800, loss 5.311782
epoch 2, step 1000, loss 17.896744
epoch 2, step 1200, loss 14.790212
epoch 2, step 1400, loss 8.898263
epoch 2, avg loss 6.322279
epoch 3, step 1600, loss 0.008326
epoch 3, step 1800, loss 2.825358
epoch 3, step 2000, loss 1.019447
epoch 3, step 2200, loss 2.831027
epoch 3, avg loss 4.785942
epoch 4, step 2400, loss 0.042604
epoch 4, step 2600, loss 1.630599
epoch 4, step 2800, loss 0.235781
epoch 4, step 3000, loss 11.383674
epoch 4, avg loss 3.816747
epoch 5, step 3200, loss 1.631361
epoch 5, step 3400, loss 11.791616
epoch 5, step 3600, loss 8.646818
epoch 5, step 3800, loss 0.330976
epoch 5, avg loss 3.119967
epoch 6, step 4000, loss 0.054771
epoch 6, step 4200, loss 1.198393
epoch 6, step 4400, loss 1.082042
epoch 6, avg loss 2.603878
epoch 7, step 4600, loss 0.303289
epoch 7, step 4800, lo

In [16]:
label_Y, predicted_Y = [], []
for k in range(0,(test_X_seq.shape[0] // batch_size)*batch_size,batch_size):
    batch_x = test_X_seq[k:k+batch_size]
    batch_length = [seq_len] * batch_size
    batch_x_char, batch_x_char_length = generate_char_seq(batch_x)
    batch_y = test_Y_seq[k:k+batch_size]
    Y_pred = sess.run(model.crf_decode,
                  feed_dict={model.word_ids:batch_x,
                             model.sequence_lengths:batch_length,
                            model.char_ids:batch_x_char,
                            model.word_lengths:batch_x_char_length})
    predicted_Y.append(Y_pred)
    label_Y.append(batch_y)

In [17]:
print(classification_report(np.vstack(label_Y).ravel(), np.vstack(predicted_Y).ravel(), target_names=tag2idx.keys()))

             precision    recall  f1-score   support

        PAD       0.98      0.98      0.98      8063
        FAC       0.99      1.00      0.99    185006
        ORG       0.99      0.95      0.97     23771
      EVENT       0.97      0.99      0.98      2600
        PRN       0.96      0.91      0.93      6080
        LOC       0.98      0.95      0.97      2120
          O       0.96      0.92      0.94      2120
        LAW       0.98      0.93      0.95     10280
       NORP       0.96      0.99      0.97      1280
       TIME       0.99      0.94      0.97      1860
        ART       0.59      0.50      0.54        20

avg / total       0.99      0.99      0.99    243200



/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1428: UserWarning: labels size, 11, does not match size of target_names, 12
  .format(len(labels), len(target_names))


In [18]:
test_string = 'Keikhlasan merupakan faktor utama yang perlu ada pada setiap pemimpin dan ahli UMNO sekiranya mahu melihat parti itu pulih kembali selain mendapat sokongan majoriti rakyat negara ini, kata Ahli Majlis Tertinggi (MT) UMNO Datuk Seri Idris Jusoh.'

In [19]:
test_X = []
for w in test_string.split():
    w = process_word(w)
    try:
        test_X.append(word2idx[w])
    except:
        test_X.append(2)

In [20]:
batch_x_char, batch_x_char_length = generate_char_seq(np.array([test_X]))

In [21]:
Y_pred = sess.run(model.crf_decode,feed_dict={model.word_ids:np.array([test_X]),
                                              model.char_ids:batch_x_char,
                                             model.sequence_lengths:[seq_len],
                                             model.word_lengths:batch_x_char_length})

In [22]:
for no, i in enumerate(test_string.split()):
    print(i,idx2tag[Y_pred[0,no]])

Keikhlasan O
merupakan O
faktor O
utama O
yang O
perlu O
ada O
pada O
setiap O
pemimpin O
dan O
ahli O
UMNO NORP
sekiranya O
mahu O
melihat O
parti O
itu O
pulih O
kembali O
selain FAC
mendapat FAC
sokongan FAC
majoriti FAC
rakyat FAC
negara FAC
ini, FAC
kata FAC
Ahli FAC
Majlis FAC
Tertinggi FAC
(MT) FAC
UMNO FAC
Datuk FAC
Seri FAC
Idris FAC
Jusoh. FAC


In [23]:
def get_entity(string):
    test_X = []
    for w in string.split():
        w = process_word(w)
        try:
            test_X.append(word2idx[w])
        except:
            test_X.append(2)
    batch_x_char, batch_x_char_length = generate_char_seq(np.array([test_X]))
    Y_pred = sess.run(model.crf_decode,feed_dict={model.word_ids:np.array([test_X]),
                                              model.char_ids:batch_x_char,
                                             model.sequence_lengths:[seq_len],
                                             model.word_lengths:batch_x_char_length})
    for no, i in enumerate(string.split()):
        print(i,idx2tag[Y_pred[0,no]])

In [24]:
get_entity('KUALA LUMPUR: Sempena sambutan Aidilfitri minggu depan, Perdana Menteri Tun Dr Mahathir Mohamad dan Menteri Pengangkutan Anthony Loke Siew Fook menitipkan pesanan khas kepada orang ramai yang mahu pulang ke kampung halaman masing-masing. Dalam video pendek terbitan Jabatan Keselamatan Jalan Raya (JKJR) itu, Dr Mahathir menasihati mereka supaya berhenti berehat dan tidur sebentar  sekiranya mengantuk ketika memandu.')

KUALA LOC
LUMPUR: LOC
Sempena O
sambutan O
Aidilfitri O
minggu TIME
depan, TIME
Perdana PRN
Menteri PRN
Tun PRN
Dr PRN
Mahathir PRN
Mohamad PRN
dan O
Menteri PRN
Pengangkutan PRN
Anthony PRN
Loke PRN
Siew PRN
Fook PRN
menitipkan EVENT
pesanan EVENT
khas EVENT
kepada EVENT
orang EVENT
ramai EVENT
yang EVENT
mahu EVENT
pulang EVENT
ke EVENT
kampung EVENT
halaman EVENT
masing-masing. EVENT
Dalam EVENT
video EVENT
pendek EVENT
terbitan EVENT
Jabatan EVENT
Keselamatan EVENT
Jalan EVENT
Raya EVENT
(JKJR) EVENT
itu, EVENT
Dr EVENT
Mahathir EVENT
menasihati EVENT
mereka EVENT
supaya EVENT
berhenti EVENT
berehat EVENT
dan EVENT
tidur EVENT
sebentar EVENT
sekiranya EVENT
mengantuk EVENT
ketika EVENT
memandu. EVENT
